### PR TITLE
Dev formatting

### PR DESCRIPTION
**Pull request by stenwall**
Some formatting! Spacing, single-quotes, indentation etc.

### CODE REVIEW

**Comment by stenwall** [comment]
accidentally added some commits from the edit_profile-branch, that's why that's the base-branch...

**Review by EnzoBomark — CHANGES_REQUESTED** [review]
First, merge dev into the branch to update content.
JSX returns should resemble HTML with double-quoted attributes.
Route exact attribute should linebreak.
Linebreak all none self closed/early closed tags.

**Comment by stenwall** [comment]
> First, merge dev into the branch to update content.
> JSX returns should resemble HTML with double-quoted attributes.
> Route exact attribute should linebreak.
> Linebreak all none self closed/early closed tags.

@EnzoBomark I think I've fixed everything on your list now! 🌈

**Review by EnzoBomark — APPROVED** [review]
Looks great! 
Feel free to merge 👍

**Pull request merged**
