### PR TITLE
Dev menu

### PR DESCRIPTION
**Pull request by jamil-source**
Chat notificartion postponed when chat part is more setup :)

### CODE REVIEW

**Comment by hannesqvarnstrom** [comment]
Fix positioning - menu is now blocking content. Try setting up a section that occupies the same amount of height the menu has, so that it's always below.

**Review by hannesqvarnstrom — CHANGES_REQUESTED** [review]
Fix positioning pls :)

**Review by EnzoBomark — CHANGES_REQUESTED** [review]
Use a higher z-index.
Fix positioning.

**Review by EnzoBomark — APPROVED** [review]
LGTM +1

**Pull request merged**
