### PR TITLE
suggestion for MIT-license

### PR DESCRIPTION
**Pull request by stenwall**
With this license, anyone may use our code, even in closed source projects. If we don't want the latter, I suggest the GNU GPLv3 license.
We could also swap the organisation name (Chas Academy) to our names instead. I think.

### CODE REVIEW

**Review by reelode — APPROVED** [review]
Should it be MIT licens and not GPL? If so, I approve and GJ!

**Comment by jamil-source** [comment]
LGTM!

**Comment by hannesqvarnstrom** [comment]
I vote for GNU!

**Review by hannesqvarnstrom — APPROVED** [review]
**chef's kiss**

**Pull request merged**
